# Generated by Django 4.2.9 on 2024-02-20 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryLists',
            fields=[
                ('ListID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='List ID')),
                ('ListName', models.CharField(max_length=255)),
                ('DateCreated', models.DateField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Product ID')),
                ('ProductName', models.CharField(max_length=255)),
                ('Category', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('StoreID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Store ID')),
                ('ChainName', models.CharField(max_length=255)),
                ('StoreName', models.CharField(max_length=255)),
                ('Location', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('PriceID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Price ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
                ('StoreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stores')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('NutritionID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Nutrition ID')),
                ('Calories', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ServingSize', models.DecimalField(decimal_places=2, max_digits=7)),
                ('FatTotal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('FatSaturated', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Protein', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Sodium', models.PositiveSmallIntegerField()),
                ('Potassium', models.PositiveSmallIntegerField()),
                ('Cholesterol', models.PositiveSmallIntegerField()),
                ('Carbohydrates', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Fiber', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Sugar', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='ListItems',
            fields=[
                ('ItemID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='List Item ID')),
                ('Quantity', models.SmallIntegerField(null=True)),
                ('Unit', models.CharField(max_length=10, null=True)),
                ('IsChecked', models.BooleanField(default=False)),
                ('ListID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.grocerylists')),
                ('PriceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.prices')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.products')),
                ('StoreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.stores')),
            ],
        ),
    ]
