# Generated by Django 4.2.9 on 2024-02-22 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chains',
            fields=[
                ('ChainID', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='Chain ID')),
                ('ChainName', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='prices',
            name='StoreID',
        ),
        migrations.RemoveField(
            model_name='stores',
            name='ChainName',
        ),
        migrations.AddField(
            model_name='prices',
            name='ChainID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.chains'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stores',
            name='ChainID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.chains'),
            preserve_default=False,
        ),
    ]
