# Generated by Django 4.2.9 on 2024-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_listitems_productid_remove_listitems_storeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitems',
            name='Quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listitems',
            name='Unit',
            field=models.CharField(blank=True, default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='Category',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
