# Generated by Django 4.2.9 on 2024-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_listitems_quantity_alter_listitems_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('BrandID', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Brand ID')),
                ('BrandName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='BrandID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.brands'),
            preserve_default=False,
        ),
    ]
